# Generated by Django 4.1.2 on 2025-01-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, null=True, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('AlterNumber', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('Address', models.TextField(max_length=200)),
                ('FunctionAddress', models.TextField(max_length=200)),
                ('EventType', models.CharField(choices=[('pre/Post-Wedding', 'pre/Post-Wedding'), ('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Engagement', 'Engagement'), ('Anniversary', 'Anniversary'), ('baby-Shower', 'baby-Shower'), ('Maternity', 'Maternity'), ('maternity', 'maternity'), ('Corporate-Event', 'Corporate-Event'), ('Others', 'Others')], max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Message', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
