# Generated by Django 4.1.2 on 2025-03-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='FunctionAddress',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Lname',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='studio_booking',
        ),
    ]
