# Generated by Django 4.1.2 on 2025-03-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0002_remove_booking_functionaddress_remove_booking_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentequipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=100)),
                ('CEmail', models.EmailField(max_length=100, null=True, unique=True)),
                ('CNumber', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('CAddress', models.TextField(max_length=200)),
                ('EquipmentType', models.CharField(choices=[('Drone Single', 'Drone'), ('LED Wall', 'LED Wall'), ('LED Plasma', 'LED Plasma'), ('Crane', 'Crane'), ('Flower Drone', 'Flower Drone'), ('varmala Drone', 'varmala Drone')], max_length=100)),
                ('EquipmentQuantity', models.IntegerField()),
                ('EquipmentDescription', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'rent_equipment',
            },
        ),
    ]
